@startwbs
* 基于GitHub的实验管理平台
** 注册
*** 登录
**** 学生模块
***** 设置个人信息
***** 修改密码
***** 选课
***** 查看成绩
***** 提交作业
**** 教师模块
***** 选课
***** 发布实验
***** 修改实验
***** 删除实验
***** 评分
***** 修改分数
***** 修改密码
***** 设置个人信息


@endwbs