@startuml
skinparam classAttributeIconSize 0
图书管理员"*" -- "*"借阅信息:登记
续借信息"1" --*  "1"借阅信息
读者"1" -- "*"预定信息
预定信息"*" -- "1"书目信息:被预定
书本"*" --|> "*"书目信息
借阅信息"*" -- "1"罚款明细
书目信息"*" -- "1"借阅信息
class 图书管理员 {
    -工号
    -姓名
}
class 读者{
    -姓名
    -身份证号
    -电话
    -借阅卡号
    -已借图书
}
class 书目信息{
    +书名
    +作者
    +印刷号
    +书籍ISBN
}
class 书本{
    +馆藏编号
    +按书目查找
    +简介
}
class 借阅信息{
    +书籍ISBN
    +借阅开始时间
    +借阅截止时间
}
class 预定信息{
    +预定日期
    +书籍ISBN
    -借阅卡号
}
class 罚款明细{
    -罚款金额
    -借阅卡号
}
class 续借信息{
    +编号
    -借阅卡号
}

@enduml