@startuml
actor 图书管理员
==申请还书阶段==
activate 图书管理员
图书管理员->登录界面:1:验证身份
activate 登录界面
登录界面->图书管理员:2：返回信息
deactivate 登录界面

读者->图书管理员:3：还书请求
activate 读者
deactivate 图书管理员
deactivate 读者
==执行还书阶段==
图书管理员->读者记录:4：扫描读者ID
activate 图书管理员
activate 读者记录
deactivate 图书管理员
读者记录->读者记录:5：记录读者还书
读者记录->图书管理员:6：返回读者消息
deactivate 读者记录
activate 图书管理员
图书管理员->还书记录:7：扫描书籍ID
activate 还书记录
还书记录->图书管理员:8：返回该书信息
deactivate 还书记录
deactivate 图书管理员
还书记录->还书记录:9：记录书记还回
activate 还书记录
还书记录->图书管理员:10：还书成功
activate 图书管理员
deactivate 还书记录
deactivate 图书管理员
@enduml