@startuml
actor 系统管理员
actor 图书管理员
actor 读者
rectangle checkout {
系统管理员-->(权限管理)
系统管理员-->(日志管理)
:系统管理员:<|--图书管理员
left to right direction
图书管理员-->(借出图书)
(审核续借请求).> (借出图书) : extends
图书管理员-->(归还图书)
(逾期开出罚款).> (归还图书) : extends
图书管理员-->(维护书目)
(维护书目)..> (购入图书) : include
(维护书目).> (丢失图书) : include
图书管理员-->(维护读者信息)
(维护读者信息)..> (添加读者) : include
(维护读者信息)..> (注销读者) : include
(维护读者信息)..> (修改密码) : include

读者-->(查询书目)
(查询书目).> (查询借阅情况) : include
读者->(预定图书)
读者-->(借阅图书)
(申请续借).> (借阅图书) : extends
读者-->(归还书籍)
(逾期缴纳罚款).> (归还书籍) : extends
(取消预订).> (预定图书) : extends
}
@enduml